%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 1  

imu_topic: "/imu/data_raw"
image_topic: "/stereo/left/image_raw"
encoder_topic: "/encoder/data_raw"
output_path: "~/output/"

model_type: PINHOLE
camera_name: camera
image_width: 1280
image_height: 560

distortion_parameters:
   k1: -5.6143027800000002e-02
   k2: 1.3952563200000001e-01
   p1: -1.2155906999999999e-03
   p2: -9.7281389999999998e-04
projection_parameters:
   fx: 7.7537235550066748e+02
   fy: 7.7537235550066748e+02
   cx: 6.1947309112548828e+02
   cy: 2.5718049049377441e+02

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation_ic: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [-0.00680499, -0.0153215, 0.99985,
           -0.999977, 0.000334627, -0.00680066,
           -0.000230383, -0.999883, -0.0153234]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation_ic: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [1.71239, 0.247401, -0.11589]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 200            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.15  # max solver itration time (ms), to guarantee real time
max_num_iterations: 15   # max solver itrations, to guarantee real time
keyframe_parallax: 5  # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. 
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     
acc_w: 0.001        # accelerometer bias random work noise standard deviation.  
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
loop_closure: 1                    # start loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 1             # useful in real-time and large project
pose_graph_save_path: "/home/xiaoqiang/output/pose_graph/" # save and load path

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ

#wheel encoder
is_encoder: 1 # is encoder
encode_resolution: 4096         # resolution of encoder
left_wheel_diameter: 0.623479   # [m]
right_wheel_diameter: 0.622806  # [m]
wheelbase: 1.52439             # [m] wheelbase, length between two wheels
enc_n: 0.2       # encoder readings noise standard deviation.

#Rotation from encoder frame to imu frame, imu^R_enc
extrinsicRotation_io: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1, 0, 0,
          0, 1, 0,
          0, 0, 1]
#Translation from encoder frame to imu frame, imu^T_enc
extrinsicTranslation_io: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.07, 0., -1.7]   # [0.07, 0., -1.7]
